### PR TITLE
Adding python functions

### PR DESCRIPTION
**Pull request by keitaroyam**
AsuData.copy() a copy constructor, SMat33.r_u_r() for numpy.array, Mat33 as numpy.array.

### CODE REVIEW

**Comment by wojdyr** [comment]
Thanks!

if you don't mind I'll change AsuData.copy() to clone(). Because in Structure, Model, etc. the copying function is named `clone`. Actually I wasn't sure if it's better to call it copy or clone when I was adding these functions, but I had to choose something.

Do you happen to know a better name for r_u_r()? I called it like this because I didn't know what's the proper name of this operation.

**Comment by keitaroyam** [comment]
Thanks for merging. No, please do so!

A better name may be preferred, but r_u_r is ok to me. In cctbx a similar function is called c_u_c_transpose (and internally tensor_transform is called)?

**Comment by sizmailov** [comment]
Sorry for jumping in the discussion once again. I think `.copy()` is more common for python libraries, e.g. numpy, pandas. It might be a good idea to stick to common python practices and naming. Recall that there are special `__copy__` and `__deepcopy__` methods for shallow and deep copy. Hope my comments are not too annoying :)

**Comment by wojdyr** [comment]
@sizmailov it's good that you are commenting. Naming things is hard.
Now I looked into git log and I see in https://github.com/project-gemmi/gemmi/issues/31#issuecomment-629434050 that I considered calling these functions `.deepcopy()`, because `.copy()` could be understood as shallow copy.
I don't have a strong opinion on this. Let's leave it as it is: AsuData.copy() and Structure.clone().

@keitaroyam thanks for checking cctbx. `c_u_c_transpose` is also cryptic, so I guess this operation doesn't have a short and clear name.

**Comment by sizmailov** [comment]
Yeah, one of the hardest problems in CS :) 

Unless C++ type store al members as `shared_ptr<T>` it should be viewed as "value type" for which "shallow copy" does not make any sense and `copy` and `deepcopy` should do exactly same thing. I _think_ the majority of all exposed gemmi types follows this pattern, so it would not create a confusion.

In general it's a good idea to keep API homogeneous as possible. If you want to keep old naming for backward compatibility it can be aliased via pybind just like in python:

```c++
pyType.attr("clone") = pyType.attr("copy"); // do same for __copy__ / __deepcopy__
```

I'm not aware if you adapted any policy about API changes across 0.x releases (or I miss something?)
IMO the best option would be to keep old API and mark it as deprecated so it would produce one-time warning in runtime. I've tried to do it in past for my own pybind library, but if I recall it right I didn't found any convenient way to do that. Maybe it's time to check it once again.

**Pull request merged**
