### PR TITLE
replaced cpp warning directive with pragma message

### PR DESCRIPTION
**Pull request by MergunFrimen**

### CODE REVIEW

**Comment by wojdyr** [comment]
it's usually good to write **why** a change is proposed

**Comment by MergunFrimen** [comment]
sorry about that, i thought it wasn't necessary since it was one line of code.

**Comment by wojdyr** [comment]
It's clear what you changed, but not why.
I'm also wondering why do you see this warning at all.

**Comment by MergunFrimen** [comment]
oh sorry again, i kept running into this warning because i'm using the libstb-dev ubuntu package. 
i thought it was odd that there needed to be a warning so i replaced it with a message instead.

**Pull request merged**
