### PR TITLE
Add missing python bindings for ccp4

### PR DESCRIPTION
**Pull request by keitaroyam**
full_cell() and axis_positions() were added.

### CODE REVIEW

**Comment by wojdyr** [comment]
the names I used for these functions are probably not good – I couldn't recollect what they do without checking it in the code

**Comment by keitaroyam** [comment]
Maybe. Any possibility to change the name?

**Comment by wojdyr** [comment]
the names could be changed  (I think you are the only person using these functions outside of gemmi), but I'm not sure how they should be named

**Comment by keitaroyam** [comment]
Obviously true at the moment :)

**Pull request merged**
