### PR TITLE
Grid::subgrid() added

### PR DESCRIPTION
**Pull request by keitaroyam**
I want to have this for EM map manipulations.

### CODE REVIEW

**Comment by wojdyr** [comment]
Some functions that operate on grid assume that it covers the whole unit cell. Especially when symmetry is involved.
We could have subgrid without space group and unit cell, but then I imagine it wouldn't be very useful.
What kind of map manipulations do you do?

**Comment by keitaroyam** [comment]
I want to crop an arbitrary region of the map, especially when read from a ccp4 map with non-zero starting grid points (NXSTART/NYSTART/NZSTART). This is something like a low-level version of Ccp4::set_extent(); I wanted to explicitly specify the extent.

With this operation space group information becomes invalid in general, so maybe it is better to return data array (not Grid object) as a python-only API?

**Comment by wojdyr** [comment]
Yes, would a numpy array be sufficient?

**Comment by keitaroyam** [comment]
OK. What should the name of the function be? Is subgrid ok?

**Comment by wojdyr** [comment]
perhaps get_subarray()?

**Comment by keitaroyam** [comment]
How is it now?

**Comment by wojdyr** [comment]
Looks good, thanks!

**Comment by keitaroyam** [comment]
Thanks for merging!

**Comment by wojdyr** [comment]
I'd like to document get_subarray() and add symmetric set_subarray().
Do I understand correctly that the advantage of get_subarray over array slicing is that it handles cell repetition (periodic boundary conditions)?

**Comment by keitaroyam** [comment]
Yes, that is why I wanted this.

**Comment by wojdyr** [comment]
get_subarray() was a very useful addition. I optimized and documented it, and added also set_subarray().
Note: the arguments has changed. Now they are grouped:

    grid.get_subarray([u0, v0, w0], [nu, nv, nw])

This should simplify the code in servalcat.

**Comment by keitaroyam** [comment]
Thank you. I need to test this. Are there any plans for the next gemmi release?

**Comment by wojdyr** [comment]
Yes, I'd like to release the next version tomorrow or day after tomorrow.

**Comment by keitaroyam** [comment]
Good. Please go ahead.

**Pull request merged**
