### PR TITLE
Fix out-of-bounds string access

### LINKED ISSUE #44: Access beyond string size in small.hpp
I am seeing a memory issue when using `gemmi::make_small_structure_from_block`. When running under [valgrind](https://valgrind.org), I get:

```
$ cat a.cpp
#include <gemmi/cif.hpp>
#include <gemmi/smcif.hpp>

int main (void) {
    auto block = gemmi::cif::read_file("1544173.cif").sole_block();
    gemmi::SmallStructure SiC = gemmi::make_small_structure_from_block(block);
}
$ g++ a.cpp -I $PWD/gemmi-0.4.1/include 
$ valgrind ./a.out                     
==2764260== Memcheck, a memory error detector
==2764260== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==2764260== Using Valgrind-3.12.0.SVN and LibVEX; rerun with -h for copyright info
==2764260== Command: ./a.out
==2764260== 
==2764260== Conditional jump or move depends on uninitialised value(s)
==2764260==    at 0x11B874: void gemmi::split_element_and_charge<gemmi::SmallStructure::Site>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, gemmi::SmallStructure::Site*) (in /home/coudert/a.out)
==2764260==    by 0x11781B: gemmi::make_small_structure_from_block(gemmi::cif::Block const&) (in /home/coudert/a.out)
==2764260==    by 0x10BBAF: main (in /home/coudert/a.out)
==2764260== 
==2764260== 
==2764260== HEAP SUMMARY:
==2764260==     in use at exit: 0 bytes in 0 blocks
==2764260==   total heap usage: 849 allocs, 849 frees, 367,416 bytes allocated
==2764260== 
==2764260== All heap blocks were freed -- no leaks are possible
==2764260== 
==2764260== For counts of detected and suppressed errors, rerun with: -v
==2764260== Use --track-origins=yes to see where uninitialised values come from
==2764260== ERROR SUMMARY: 50 errors from 1 contexts (suppressed: 0 from 0)
```

With another valgrind version, a slightly different message but I think it is the same issue:

```
==17170== Memcheck, a memory error detector
==17170== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==17170== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==17170== Command: ./cif
==17170== 
==17170== Invalid read of size 1
==17170==    at 0x6B545C: void gemmi::split_element_and_charge<gemmi::SmallStructure::Site>(std::string const&, gemmi::SmallStructure::Site*) (small.hpp:77)
==17170==    by 0x6B1CB4: gemmi::make_small_structure_from_block(gemmi::cif::Block const&) (smcif.hpp:73)
==17170==    by 0x6A4AD5: chemfiles::CIFFormat::init_() (CIF.cpp:67)
==17170==    by 0x5E6EB1: chemfiles::CIFFormat::CIFFormat(std::string, chemfiles::File::Mode, chemfiles::File::Compression) (CIF.hpp:36)
```

### PR DESCRIPTION
**Pull request by fxcoudert**
Fixes #44

### CODE REVIEW

**Comment by fxcoudert** [comment]
@wojdyr please review, I think this bug was introduced by you :) https://github.com/project-gemmi/gemmi/commit/1a159f118e44b1bbcf6616b99ef94a81e9df8b26#r41018952

**Comment by wojdyr** [comment]
Thanks for investigating and fixing it!
When looking at this code I wonder if CIF files also have +/- without numbers, i.e. `A+` or `A-`, but that's a different thing.

**Comment by fxcoudert** [comment]
Actually, I am surprised that this provides useful charges. For example, suppose there are 12 carbon atoms, with labels `C1` to `C12`… the code will interpret them as having charges 1, 2, …, to 9, then 1 again (for `C10`, `C11` and `C12`). That does not appear correct to me.

**Comment by wojdyr** [comment]
Indeed. I'll change it to assign charge only if it has +/- at the end.

**Pull request merged**
