### PR TITLE
add missing python bindings for SMat33 and Mat33

### PR DESCRIPTION
**Pull request by keitaroyam**
I wanted to use `Mat33.multiply_by_diagonal()`. I have also added the others.

### CODE REVIEW

**Comment by keitaroyam** [comment]
I found `atom.aniso = atom.aniso.transformed_by(mat33)` did not work because of type mismatch (SMat33f vs SMat33d). Is there any simple workaround?

**Comment by wojdyr** [comment]
I added `Mat33.multiply_by_diagonal()` and a few other functions from this PR.
I don't want to add all of them if they are not needed yet. Generally, the missing bindings are not there because I'm not sure if they will be useful or because the functions may change in the future. If any of them is needed let me know.

I also changed `transformed_by` to return the same type.

**Comment by keitaroyam** [comment]
OK, thanks.

**Comment by keitaroyam** [comment]
Now I want to use `added_kI()` - you do not want to add a binding?

**Comment by wojdyr** [comment]
OK, added.

**Comment by keitaroyam** [comment]
Thank you!

**Pull request closed without merging**
