### PR TITLE
add python functions for Grid

### PR DESCRIPTION
**Pull request by keitaroyam**
- Grid properties: shape and spacing
- Add cell and sg arguments for Grid constructor 
- Grid. point_to_position() directly from u, v, w

### CODE REVIEW

**Comment by wojdyr** [comment]
Could `spacing` be a list or a tuple? It could also be changed std::array on the C++ side.

The change to the constructor has a side effect that one of the CI checks above fails (the CI jobs are not completely configured yet, this is the only one that builds python bindings). It seems that the second ctor is tried if you don't specify optional arguments. You can test it with disabled numpy:

```
import sys
sys.modules['numpy']=None
import gemmi
gemmi.FloatGrid(3,3,3)
```

**Comment by keitaroyam** [comment]
I tried grid.spacing[0]=0, but grid.spacing remained unchanged. AttributeError was raised by grid.spacing*=0.

**Comment by wojdyr** [comment]
yes, that's a problem in many places. It's covered here:
https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html#making-opaque-types
(but making this type opaque would have downsides here, the same type would need to be opaque also in all other files).
Alternatively, you could make it read/write and only do `grid.spacing = [0, 0, 0]`.

**Comment by keitaroyam** [comment]
OK, I changed it to tuple. How about this?

**Comment by wojdyr** [comment]
That's fine. There is also the problem with constructor – it's a separate problem.

**Comment by keitaroyam** [comment]
Do you know how to solve this problem? Or can we expect numpy is always there?

**Comment by wojdyr** [comment]
I tried various things. Adding `py::kw_only()` after the first py::arg() in the last constructor solves this problem, but creates another one: `None` is not handled for spacegroup and cell in that constructor (perhaps it's a bug in pybind11).
So I haven't found a solution.
Setting only unit cell (not space group) in both constructors would probably work, as the number of args would be always different.

**Comment by keitaroyam** [comment]
Many thanks for this. I personally feel we can assume numpy is available, but I can omit this constructor change in this pull request.

**Comment by wojdyr** [comment]
I'd rather omit it. Importing numpy when creating a grid that may not even use numpy doesn't feel right to me.

**Comment by keitaroyam** [comment]
That makes sense. I omitted it. I hope this problem will be solved in the future.

**Pull request merged**
