### PR TITLE
Add basic auto-generated python API

### PR DESCRIPTION
**Pull request by sizmailov**
Hi! I find this library well designed and quite helpful. Unfortunately currently documentation lacks full python API which makes work with the library a bit tedious. Even PyCharm introspection of binary modules fails shortly with pybind11 modules. 

This PR aims to partially fill this gap. 

A bit of trickery is used to make pybind11-generated docstring fit into sphinx ecosystem. It's still far from perfect, but much better than defaults.

Preview: https://sizmailov.github.io/gemmi/api/python/

Drawbacks:
 - requires installed `gemmi` module (i.e. cannot be build at readthedocs, possible alternative: travis + github pages)
 - sphinx-versioning is not readily supported: it's hard to unload binary modules, if even possible, so auto-generated API ends up same for all the versions. May be API can be hosted separately. On my own project I gave up on versioning. 
 - [not related to PR itself] currently there is a number of undocumented functions/attributes/classes

I mark this PR as draft since it has unresolved issues. 

Hope you'll find it helpful. 
Cheers!

### CODE REVIEW

**Comment by sizmailov** [comment]
Order of pybind11 bindings affects generated docstrings (altough runtime is essentially not affected). 

I've done a bit of module initialization reorder and "forward declaration" of bindings to eliminate C++ signatures from docstings (see regenerated [API](https://sizmailov.github.io/gemmi/python-api.html)). 

The C++ signatures that left correspond to non-bound enumerations (`gemmi::El` and `gemmi::ChemLink::Group`). Lack of explicit binding is not an error since returned values are implicitly converted to integers.

**Comment by wojdyr** [comment]
Hi Sergei
thanks for your work.
I didn't look into details yet, but the output seems to be similar to what you get from pydoc, but of course with nice html formatting. By pydoc I mean:

    pydoc gemmi

or

    python -m pydoc gemmi

**Comment by sizmailov** [comment]
No surprise. Pretty much any doc generation tool would produce similar results. I don't insist on sphinx autodoc tool, but it seems to be quite natural choice given style of rest of documentation. 

<details><summary> pydoc suffer from C++ signatures too (recent master):</summary>

image

</details>

**Comment by sizmailov** [comment]
Here is result of another (quite decent) doc generator `m.css` with built-in pybind11 modules support:
https://sizmailov.github.io/gemmi/m.css/
`m.css` also integrates with doxygen so it might serve C++ API reference too.

**Comment by wojdyr** [comment]
It looks great!
I'll be happy to put it under project-gemmi.github.io/ (the main page currently redirects to RTD, but other pages can be used).

I think this page would be the best entry point:
https://sizmailov.github.io/gemmi/m.css/gemmi.html
so I'd link from sphinx documentation to gemmi.html

**Comment by sizmailov** [comment]
I've updated PR. 

Generated docs (in `docs/_build/html/`) can be uploaded to `gh-pages` branch, so github.io won't redirect to readthedocs anymore, but will host it's copy+API instead. readthedocs can be updated to include link to Python API. I think github.io can be viewed as "main" documentation from now, while readthedocs can still be maintained for compatibility. 

To build all docs locally do the following: 
```sh 
cd docs; 
make html                      # generate sphinx part of doc 
bash build_api_reference.sh    # generates python API under `_build/html/api/python/`
```

I made `api/python` subdirectory for python API to leave room for C++ docs.

**Comment by wojdyr** [comment]
Thanks, it's much appreciated! I'll try it out later this week or next week.

**Comment by sizmailov** [comment]
I've updated PR to include C++ reference as well. 
Demo is uploaded to https://sizmailov.github.io/gemmi/

Note that various Doxygen versions have different bugs so your results (if any) might be different from what I get. I use custom built doxygen from [here](https://github.com/mosra/doxygen/tree/mosra-master). 

Right now API pages might look a bit orphaned, but it's not a bad start I guess.

**Comment by sizmailov** [comment]
Hi! Here is a quick update of the PR. 

A couple of related PRs were recently merged/closed. mcss now has better pybind11 type parsing support and pybind11 itself generates a bit better docstrings. Pybind also get a minor improvement in docstring generation.

Unfortunately typed iterators PR was rejected by Wenzel, so it might be tricky to get all type information automatically with non-patched version of pybind11. Patched version still might be used to  generate online doc.

I would be happy to help here.

**Comment by wojdyr** [comment]
Thanks for this work!
I uploaded Python API documentation here:

https://project-gemmi.github.io/python-api/

I didn't use the Sphinx inter-linking extension. I think the only difference is that I don't have links to int, bool, str, etc in Python documentation, and to ndarray in numpy documentation. These types are widely known, so I'd rather skip these links.

I'm inclined to not use Doxygen. Because without annotations it's not particularly useful, and because many functions that get listed are meant for internal use only.

I'll add a link to it from the main documentation soon.

**Pull request closed without merging**
