### PR TITLE
model: ignore segment in atom_matches

### PR DESCRIPTION
**Pull request by keitaroyam**
related to #121

### CODE REVIEW

**Comment by wojdyr** [comment]
It can be confusing if segment IDs are sometimes taken into account and sometimes ignored.
To keep track when they are ignored:

#121 was for writing links in PDB
#122 the same for mmCIF
#126 - something with topology
#128 (this one) - in atom_matches() which is used in find_connection_by_cra().

I guess in general segment IDs should be considered, because the main purpose of these IDs in the PDB format is to distinguish atoms with the same chain and residue IDs.

In the first two cases segment IDs were ignored because they are absent in the LINK records anyway.

Should we assume that Connection::partnerN has always blank segment ID and is applicable to all segments?

**Comment by keitaroyam** [comment]
Sorry for making similar requests repeatedly; I made each when I found it was needed.

I think segment IDs should be ignored in these cases because source of `st.connections` is LINK records. The problem may arise when multiple atoms (with different segment IDs) are matched. So the general solution would be to assume Connection::partnerN corresponds to multiple atoms? I guess in most cases just ignoring segment (like these pull requests) would work though.

In addition, maybe `st.connections` should also be expanded in `st.expand_ncs()`?

**Comment by wojdyr** [comment]
No problem with requests.

Let's assume that `expand_ncs()` creates N chains from a single one. If we ignore segment ID, each Connection can be matched to N^2 atom pairs instead of N.

Perhaps segment ID of the original atoms should be left empty?

Or, as you wrote, connections should be expanded?

Or both?

**Comment by keitaroyam** [comment]
It's true! Both options sound good to me. `Dup` cannot be used if the user intentionally used segment IDs. It would be rare though.

**Comment by wojdyr** [comment]
I added both options, although without testing.
expand_ncs has now option `copy_connections` (False by default) that's implemented only for Dup.
I'll get back to it later on and implement it for other HowToNameCopiedChain.
And then, perhaps copy_connections should be True by default.

**Comment by wojdyr** [comment]
I changed `expand_ncs()` again.
Now connections are always copied and `copy_connections` argument is removed (to make it simpler).
I reverted back to setting segment to "0" in the original chain for Dup, although I'm not sure about it.

I think that 121, 122 and 126 can be reverted now - I'll look into it next week.

**Comment by keitaroyam** [comment]
A related question: if LINK(R) headers are duplicated, then `st.connections` have duplicated `Connection`s when the file is read into gemmi. Does it cause any harm? For example it will lead to duplicated `TopoExtraLinks`. `TopoForces` will be also duplicated?

**Comment by wojdyr** [comment]
I don't know. Before the file is written and the segment IDs are there all should be fine (if #126 is reverted).
After segment IDs are lost - I guess it won't work as expected.

**Comment by keitaroyam** [comment]
OK, it seems I need to take care of these things.

**Comment by wojdyr** [comment]
Perhaps we can think of another solution.
Why do you need to write a model with expanded NCS to a file?

**Comment by keitaroyam** [comment]
In my pipeline (Servalcat) the expanded model is written for user's inspection when the model is refined with point group symmetry. For example user can make sure that the correct NCS operators are used.

**Pull request closed without merging**
