### PR TITLE
monlib: read nucleus distances in modifications

### PR DESCRIPTION
**Pull request by keitaroyam**
New monomer library (in bzr, not yet in ccp4) includes nucleus distances for modifications.

### CODE REVIEW

**Comment by CV-GPhL** [comment]
A note of caution here: eLBOW/Phenix seems to create restraint dictionaries using another convention with
```
loop_
_chem_comp_bond.comp_id
_chem_comp_bond.atom_id_1
_chem_comp_bond.atom_id_2
_chem_comp_bond.type
_chem_comp_bond.value_dist
_chem_comp_bond.value_dist_esd
_chem_comp_bond.value_dist_neutron
```
See [geostd](https://github.com/phenix-project/geostd) for further examples. Here you need to read the nucleus distance from ``_chem_comp_bond.value_dist_neutron``, but the esd from ``_chem_comp_bond.value_dist_esd``.

Of course, it might've been better to agree on a standard before adding these variants. I would've thought that a better solution to be
- ``value_dist`` and ``value_dist_esd`` being the default (nucleus positions, available for all atoms and bonds and independent of usage or type of experimental data)
- ``value_dist_ecloud`` and ``value_dist_ecloud_esd`` defining the special case (only hydrogens and X-Ray data have a different value here)

**Comment by GaribMurshudov** [comment]
Since we are at very early stages we can change the names. At the moment only gemmi and one of Lucrezia's program would be affected. 
I am not very sensitive to names as soon as the contents is what we want. If you have strong opinions we cqn chnage them.

**Comment by wojdyr** [comment]
I didn't know that PHENIX has publicly available restraint dictionary. When I have time I'll try to make gemmi read it.
I see that geostd has had neutron distances since 2012, so I suppose it'd be hard to change the naming there now.
Another question is: do we need `value_dist_nucleus_esd`?

(in the meantime I'll merge this PR to not block what Keitaro is working on)

**Comment by GaribMurshudov** [comment]
I think we do need esd for this seperately. We may get away without that but for completeness it would be better to have this.

**Comment by pemsley** [comment]
I think that "x_nucleus" should be changed to "x_nuclear"

**Comment by wojdyr** [comment]
Let's also ask PHENIX developers for opinion.
@nwmoriarty @pafonine @terwill (actually I'm not sure who deals with restraints there)
The naming of bond distances in restraint dictionaries diverged.
Refmac started using `value_dist_nucleus_esd` – equivalent to `value_dist_neutron` in geostd.
Grade2 and Buster started using a different scheme (with `_ecloud` for electron distances?).
We could discuss it and agree on the same naming, but is it possible to do this kind of changes in geostd and PHENIX?

**Comment by CV-GPhL** [comment]
To clarify:

- BUSTER supports both the CCP4 (``value_dist_nucleus`` and ``value_dist_nucleus_esd``) and the PHENIX (``value_dist_neutron``) extension, so either of those restraint dictionaries should work when given to BUSTER
- Grade2 generates combo dictionaries the same way as CCP4 (``value_dist_nucleus`` and ``value_dist_nucleus_esd`` on top of the PDBx/mmCIF standard ``value_dist`` and ``value_dist_esd``  items).
- Grade only generates PDBx/mmCIF standard ``value_dist`` and ``value_dist_esd``  items (nucleus distance by default, but e-cloud for X-H on demand).

**Comment by CV-GPhL** [comment]
> I think that "value_dist_nucleus" should be changed to "value_dist_nuclear" likewise the esd (which I think we _do_ want)

Can you clarify why you prefer "nuclear" to "nucleus"? I always thought of an atom consisting of a nucleus (neutrons and protons) and surrounding electrons (resulting in "e-cloud" naming) ...

**Comment by nwmoriarty** [comment]
I can field most of the questions about  GeoStd but I seem to be only
getting a fraction of the correspondence. This may be due to all people in
the conversation not "Reply to all"-ing.

To answer some of your questions. I could change the GeoStd but will need
to change the Phenix code-based as well so it will not be instantaneous.

Regarding the "nucleus"/"nuclear" choice, the current choice seems the best
to me. The dictionary definition of nuclear is "relating to the nucleus" so
why have an indirect meaning.

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Phone : 510-486-5709     Email : ***@***.***
Fax   : 510-486-5909      Web  : CCI.LBL.gov
ORCID : orcid.org/0000-0001-8857-9464

**Comment by wojdyr** [comment]
@nwmoriarty the discussion is public on Github. You can read it all by clicking the link at the bottom of the email notification.

**Comment by GaribMurshudov** [comment]
I think we can agree on one of the definitions and then change our software to make it backward compatable.
My preferred choice is nucleus for nuclear distances. Second choice would be value_dist for protons (nuclear distances) and ecloud for electrons.

**Comment by nwmoriarty** [comment]
I'd push back on the whole ecloud thing because the X-H in the monomer library have always been ecloud distances. Granted it would be nice to be clear but historical precedent is a large inertial force in computer code. Also changing to ecloud and nucleus means that backwards compatibility would be very complicated. GeoStd can move the "value_dist_nucleus" and "value_dist_nucleus_esd" in the short term. Voting against changing "value_dist" and "value_dist_esd".

**Comment by GaribMurshudov** [comment]
If everyone agrees then we go for "value_dist_nucleus" and "value_dist_nucleus_esd" 
And change our software to make them backward compatable.

**Comment by wojdyr** [comment]
Can we make `value_dist_nucleus_esd` optional?
With the interpretation that if it is absent then `value_dist_esd` applies? (as it does now for `_neutron`)
This should simplify the changes – `value_dist_neutron` is used in a number of places:
https://github.com/search?q=value_dist_neutron&type=code

**Comment by CV-GPhL** [comment]
@wojdyr: Regarding your [github search](https://github.com/search?q=value_dist_neutron&type=code): most of those hits are not actually in code, but in CIF files. Is there a way of filtering out those and see where we actually have real code?

@nwmoriarty: I can follow your argument about history and ``value_dist``/``value_dist_esd`` being traditionally used for X-H ecloud distances. We should probably update the dictionary definition with some explanation to that effect. This can come as a larger effort to better describe/define mmCIF restraint dictionaries.

What we seem to converge towards is
```
value_dist                          # (mandatory) e-cloud distance for X-H, otherwise nucleus-nucleus distance
value_dist_esd                      # (mandatory)
value_dist_nucleus                  # nucleus-nucleus distance
value_dist_nucleus_esd              # (optional, but recommended if value_dist_nucleus given)
```
Or would ``value_dist`` always be the (e-cloud)-(e-cloud) distance - for any two atoms?

**Comment by wojdyr** [comment]
Clemens: you can filter by programing language or file extension in the advanced search.

If you think about adding it to the official PDBx/mmCIF, you must expect that it will get prefixed with `pdbx_`, which will make it even less readable. The same about other items that are used in monomer libraries but absent from the dictionary. As long as prefixing is deemed necessary, IMO updating PDBx/mmCIF is not worth it.

**Comment by CV-GPhL** [comment]
If we want to deposit restraint dictionaries into the PDB (which I think we **definitely** do/should), then the file at the time of deposition needs to conform with the PDBx/mmCIF dictionary. So ultimately we do need to work within the PDBx/mmCIF frame. That does not necessarily mean that we need to have a PDBx/mmCIF conforming restraint mmCIF file already as a working format during refinement: there could be an on-the-fly translation from categories/items used in the working format restraint dictionary to a deposition-ready file - as we do at the moment e.g. for ``_chem_comp_atom.{x,y,z}`` into ``_chem_comp_atom.model_Cartn_{x,y,z}``.

There is still a benefit of having "a" dictionary that describes and defines the restraint mmCIF files produced and used by MX software in their current format (i.e. without "pdbx_" prefixing): it would be a point of reference for us and could consolidate the already existing interoperability (between restraint generators, refinement programs and other users like Coot) as well as helping software developments. The step from a working format valid according to dictionary A to a deposition format valid according to dictionary B is then much easier I think.

**Comment by wojdyr** [comment]
I fully agree we should have restraints deposited and stored in the PDB.

My concern is that if we start discussing _nucleus now in the PDBx/mmCIF WG, we might end up with a non-optimal `pdbx_`-prefixed variant. But if we wait until the PDB is ready to include restraints in coordinate files (which may be in 5 or 25 years), it may happen that at that point the prefix policy is already dropped.

IMO the restraints should be included in the same way the "updated" mmCIF files from PDBe include connectivity.
Background: The wwPDB is apparently against including connectivity in coordinate files, despite many [problems][1] it causes. Each PDB site provides a different workaround for this: MMTF (RCSB), mmJSON (PDBj) or "updated" mmCIF (PDBe) files. The PDBe files, which have been around for >5 years, add category `chem_comp_bond` to the normal ("archived") mmCIF files. We need the same category for restraints, and a few more.

So I think the first step for archiving restraints should be for the PDB to include in the coordinate files the restraint data that is already defined in the mmCIF spec. When this is on the horizon, we could start thinking about extending the dictionary.

[1]: https://www.cgl.ucsf.edu/chimera/data/mmcif-oct2013/mmcif.html

**Comment by wojdyr** [comment]
See "Downloads" in any entry on the PDBe website. For example:
 
[Archive mmCIF file](https://www.ebi.ac.uk/pdbe/entry-files/download/1mru.cif)
[Updated mmCIF file](https://www.ebi.ac.uk/pdbe/entry-files/download/1mru_updated.cif)
…

The article about it is here: https://doi.org/10.1093/nar/gkv1047

**Pull request merged**
