### PR TITLE
python: add ChainNameGenerator

### PR DESCRIPTION
**Pull request by keitaroyam**

### CODE REVIEW

**Comment by wojdyr** [comment]
I added this class without thinking much how the interface should look like, so I'd rather not expose everything to Python.
How do you want to use it?

**Comment by keitaroyam** [comment]
I only need `make_new_name()` and the constructor from Model. Is it ok?

I want to use it with the following reason: I need to take care of special position when expanding point group symmetry. I first expand the symmetry with `HowToNameCopiedChain.Dup` and then find atoms on special positions (overlapped atoms with different `segment`). However, it seems that segment IDs are not useful to users (as they are not considered in real space refinement in COOT etc). So I want to rename chain IDs after expansion.

**Comment by wojdyr** [comment]
Do you expand it with `make_assembly`?
I probably haven't considered atoms on special positions there.
Perhaps it'd be better to handle it inside `make_assembly`?

**Comment by keitaroyam** [comment]
I use `expand_ncs()`. Of course it would be very nice if it takes care of special positions. In that case you would not add python binding for ChainNameGenerator?

**Comment by wojdyr** [comment]
Yes, unless you need it for something else.

As for renaming chain IDs after expansion: gemmi-convert has option `--segment-as-chain` that does something similar. If it'd be useful I can move this functionality to the library and add python bindings.

What do you do when you find overlapping atoms? I guess you merge them, but what about chains and residues? Is the atom at special position just removed from other residues?
Do you have an example of a PDB file with such NCS?

**Comment by keitaroyam** [comment]
Thanks, `split_by_segments()` looks useful in this case.

I use `gemmi.ContactSearch` to find contacts. This is a bit dirty way but I did not come up with a better idea.
https://github.com/keitaroyam/servalcat/blob/70e5b9a081e41b59d7186397bf3a7b4b99281f9a/servalcat/utils/model.py#L312
Yes I remove atoms from other residues. When writing this code I thought maybe gemmi should allow empty residues/chains (but I do not know if it is a good idea).

7a4m (A/201/FE and A/406/O) and 7a5v (A/5409/CL) would be good examples.

**Comment by wojdyr** [comment]
I added function Model.split_chains_by_segments(). It appends segment name to chain name.
If needed, I can customize the naming scheme.

I haven't checked how empty chains/residues would work, but in principle they should be allowed. Have you come across any problems? BTW, there is a function for removing empty chains: `Structure.remove_empty_chains()`.

I'll look into handling overlapping atoms next week.

**Comment by keitaroyam** [comment]
Thank you! I will try it now.

If I recall correctly for example Model.all() failed, as it tries to get a pointer of first element.

**Comment by keitaroyam** [comment]
This may give a duplicated chain name (for example if "A0" already existed)?
https://github.com/project-gemmi/gemmi/blob/840de30eedb0aa350dd00fcb955e88bee961459b/include/gemmi/assembly.hpp#L272

**Comment by wojdyr** [comment]
I've fixed Model.all() - it should work now.

Yes, the chain names could get duplicated in special cases, although not if single-character chain names were used as in the official PDB format. Now I added option HowToNameCopiedChain to split_chains_by_segments() to provide some alternatives.

**Comment by keitaroyam** [comment]
Thank you!

For split_chains_by_segments(), probably we should not pass `model` to `ChainNameGenerator`, because I think we usually want to use original chain IDs for original (asu) chains?
https://github.com/project-gemmi/gemmi/commit/7e49ba31b018a64c32146c8424c445fa767141c0#diff-8d14618f337c42f49d1d0c2fd73b2381d0834c7fa2248217228bd13e46ba64c2R296

**Comment by wojdyr** [comment]
yes, fixed.

**Comment by keitaroyam** [comment]
thank you!

**Comment by wojdyr** [comment]
I've just added function `merge_atoms_in_expanded_model()` that merges such overlapping atoms resulting from `expand_ncs` or `make_assembly`.
https://gemmi.readthedocs.io/en/latest/mol.html#common-operations

**Comment by keitaroyam** [comment]
I checked 29c57ab1 and it worked nicely! Thank you very much.

**Pull request closed without merging**
