### PR TITLE
MTRIX record: write identity operator first

### PR DESCRIPTION
**Pull request by keitaroyam**
Gemmi ignores identity operator when reading, but it is needed when writing?

### CODE REVIEW

**Comment by wojdyr** [comment]
I don't think the identity MTRIX is necessary. From what I remember there are files that don't have it. Is any program complaining if the identity is absent?

**Comment by keitaroyam** [comment]
As wwPDB-provided files always include identity operator, I thought it would be good to have for consistency. At least some cctbx programs seem to need it (for example `phenix.pdb.mtrix_reconstruction`).

**Comment by sizmailov** [comment]
Identity transform does not contain extra information. I think extra printing should be activated *conditionally* (e.g. by some flag) if such output is desirable. At the same time, shouldn't be `phenix.pdb.mtrix_reconstruction` (and others) more permissive and accept identity-less inputs?

**Comment by sizmailov** [comment]
If I'm reading it right, the [PDB standard](http://www.wwpdb.org/documentation/file-format-content/format33/sect8.html#MTRIXn) suggests that `MTRIXn` records should not appear for P1 unit cells? 

> The MTRIXn (n = 1, 2, or 3) records present transformations expressing non-crystallographic symmetry.  MTRIXn will appear only when such transformations are required to generate an entire asymmetric unit, such as a large viral structure.

**Comment by keitaroyam** [comment]
MTRIXn is to generate an entire asymmetric unit (not the unit cell), so it can happen in P1.

Another confusion is that simply opening-and-writing file results in change of contents (removal of identity operator). It may be better to add an option to keep identity operator when reading?

**Comment by wojdyr** [comment]
I'm quite sure I've seen PDB entries without the identity MTRIX (and without the corresponding mmCIF data), but possibly the files were regenerated in the meantime.

If identity was stored with other operators, we'd need to check if it's present when using NCS operations, so I'd rather add it when writing (as was originally proposed). I'll get back to it on Monday.

**Comment by keitaroyam** [comment]
I checked PDB entries, and you are right; there were many entries without identity operators. Probably my previous observation was biased (Refmac writes identity operator for ncs contraints because identity operator is required in input). Sorry about this.

For those entries my patch should not be applied, as id conflicts.

**Comment by wojdyr** [comment]
ok, I can add a flag in Structure (such as `explicit_identity_ncs`) to preserve it between reading and writing.

**Comment by sizmailov** [comment]
@keitaroyam, you are right, I meant to say "asymmetric unit with one molecule" but confused it with unit cell :disappointed:, but the rest of the statement still holds.

**Comment by keitaroyam** [comment]
@wojdyr I am happy with that way. Thank you.

**Pull request closed without merging**
